response:
  type: application/xml
  body:
    template: <?xml version="1.0" encoding="utf-8"?>
            <string xmlns="http://entinfo.cn">
              <%= request.query.rrid %>
            </string>
